### ISSUE TITLE
Does not offer the functions (sum, min, max, ...) when the type is integer64 or double

### ISSUE THREAD

**Issue by FERRATON** [juliepierson/DissolveWithStats#7]
see attachment
![2016-06-21_09h37_46](https://cloud.githubusercontent.com/assets/2129643/16221670/69cb332a-3794-11e6-9443-9c73b75369c9.png)

**Comment by FERRATON** [comment]
ligne 183 du module dissolve_stats_dialog.py
 # if field is numeric
 if fields[i].type() in [2, 4, 6] :
    listStat.addItems(statNum)

**Comment by juliepierson** [comment]
Done, thanks !
